name: The Open Globe Project
markdown: redcarpet
pygments: false
timezone: America/New_York
permalink: none

# Explicit excludes, including dotfiles to be safe
exclude: [.DS_Store, .git, .gitignore, .vagrant, Gruntfile.js, Vagrantfile, package.json, node_modules]
